#This is a samply config file.  Create a file named conf.py,in this directory, and decalre the following variables there.
#DO NOT EDIT THIS FILE.  This file is not read for config changes
APPURL = ('http://y.a11y.in',)  # The path which points to "alipi" directory.
JQUERYURL = ('http://foo.jquery',)  # URL for jquery.
JQUERYUI = ('http://y.a11y.in/apis',)  # URL for loading jQuery UI theme and widgets
JQUERYCSS = ('http://y.a11y.in/apis',)  # URL for loading custom jQuery CSS
BLOGURL = ('http://something.blogspot.com',)  # Temporarily deprecated.
EMAIL = ('johnDoe@gmail.com',)  # Deprecated
DEPLOYURL = ('http://y.a11y.in/app',)  # URL pointing to the application
DBNAME = ('test',)  # mySQL db for holding a list of language and location
DBPASSWD = ('admin',)  # mySQL password
DBUSRNAME = ('sql_password',)  # mySQL user with read access to the DBNAME
DBHOST = ('localhost',)
MONGODB = ('dev_alipi',)
MONGOHOST = ('127.0.0.1')
SWEETURL = ('http://localhost:5001',)
SWEET_STORE_ADD = ("http://localhost:5001/api/sweets",)
SECRET_KEY = ('a random secure string, see python UUID for more',)
CUSTOM_BLOG_POST_URL = ('http://localhost:5002/page',)
CUSTOM_BLOG_URL = ('http://localhost:5002',)
APP_ID = 'your app id from sweet store'
APP_SECRET = 'your app secret from sweet store'
REDIRECT_URI = "http://localhost:5000/redirect"
RECAPTCHA_URL = "https://www.google.com/recaptcha/api/siteverify"
RECAPTCHA_SECRET = "secret provided by reCAPTCHA service provider"