#+AUTHOR Sai Gollapudi

* Intro
The objective of this document is to capture the thinking and logic
behind some of the ontology decisions we are making in the renarration
project. This document also contains some useful links to papers,
tools, tutorials that we leveraged in designing our Ontologies.

For release r0 of NPTEL oriented renarration demo tool we are planning to consider a University ontology from
Education domain. As an instance we are imagining a JNTU type
University (from Hyderabad, India area) which has 100s of affiliated
colleges throughout AP and Telangana, with each having their own large set of faculty etc. 

* Useful Links
Here is where we have lot of JNTU affiliated college info. They can
also be found here. 

We have also been using [[http://protege.stanford.edu/publications/ontology_development/ontology101-noy-mcg] [this]] Stanford  Protege begginner's guidelines
paper on ontology. According to the Stanford Protege paper, there are
few steps to follow, we have used that structure below in developing
our ontology.

* Step-by-step process of design
** step 1: determining domain & scope of the ontology
Here are some basic questions they asked of us for Knowledge Engineering our Ontology. My answers are included below each of the four question.

1. What is the domain that the ontology will cover?
Education institutions / University
students -> registeredDegree, registeredProgram
affiliates ->faculty (teaches)
programs -> curriculum -> syallabus -> course details/topics
2.  For what we are going to use the ontology?
  + To identify the university / affiliate the student belongs to
  + To identify the key topics that are covered in a course
  + To identify the context, intent of a renarrator & student

3. For what types of questions the information in the ontology should provide answers?
  + What universities exist?
  + What affliated colleges exist for this university?
  + What degree programs are offered by this institution (Btech, Mtech...)?
  + What fields of study are offered by this institution (CSE, Mathematics, ECE...)?
  + What is the syllabus for this degree program (Mtech) in this field of study (CSE)? Expecting a course list.
  + What is the syllabus for the yr and semester given for a program? Expecting a semester schedule
  + What is the syllabus for this course (Intro to Quantum Physics)? Expecting to see a course description
  + Who teaches this course at this institution for this __ yr, __ semester? Expecting a faculty name
  + Who is enrolled in this class? Expecting a list of students
  + Who is the curator / coordinator / faculty  / TA / student_list for this course?
  + What is covered in this course?

4. Who will use and maintain the ontology?
  + Admin for education technologies to fill the instances of this ontology as and when the course info changes
  + will depend on university filled-in databases
  + may work with University to get the affiliates to fill in their info
  + students may have to enroll or register themselves

** step 2: Considering reusing existing ontologies
I found some vocabularies at:
+ a university vocab - http://vocab.org/aiiso/ 
+ a university ontology  in SHOE - https://www.cs.umd.edu/projects/plus/SHOE/onts/univ1.0.html 

IEEE paper on construction of a Unversity Ontology - http://ieeexplore.ieee.org/xpl/login.jsp?tp=&arnumber=6409047&url=http%3A%2F%2Fieeexplore.ieee.org%2Fxpls%2Fabs_all.jsp%3Farnumber%3D6409047
+ a university ontology in OWL / Protege; a research paper published as PDF - http://www.ijser.org/researchpaper%5CDeveloping_University_Ontology.pdf 
+ a educational institution vocabulary
+ a balogna process education institution
+ a corporate
+ here is a Protege 4.1 based OWL ontology [[http://www.ijser.org/researchpaper%5CDeveloping_University_Ontology.pdf][paper  of university]]. It claims to
  expand upon similar work by and .

+ a semantic web approach dealing with university courses is give in
  this [[http://brage.bibsys.no/xmlui/bitstream/id/88485/Shahzad,%20Muhammad%20Oppgave.pdfma][masters thesis]].

** step 3: Enumerate important terms in the ontology
What are the terms we would like to talk about? 
+ university
+ college
+ syllabus
+ course
+ student
+ program
+ degree

1. What properties do those terms have? What would we like to say about those terms? 
   + University has affiliates
   + A college registers into a university
   + A unversity / college is an educational institution
   + Educational instituition follows a curriculum
   + Educational institutions offer degree programs
   + A degree has a several year and several semester program that one must follow
   + A program is a set of courses that are offered over several years and semesters
   + A course has a syllabus
   + A course is taught by faculty
   + A course has a attributes like theory, credits, lab
   + A course has reading materials
   + A course has references, textbooks, faculty, exams, 
   + A exam has set of questions, types of questions, overall marks, timeline, offeredOn, midterm/ unit / end-exam type,
   + A question has an answer, marks
   + A faculty teaches a set of courses
   + student (saigo) registers into a university(JNTU) / college (Shivaji) for a degree (BTech) program in a particular field (CSE). This degree program is one of many programs (Btech, Mtech, PhD) the university has. The degree program will conform to a curriculum (R13) which gives the syallabus (what to cover in each unit, learning objectives...)

Here is a vocabulary list from an old ontology that may not be OWL: http://vocab.org/aiiso/ 

** step 4: Define the classes and the class hierarchy
*** Top-Down approach
Educational Instituitions (EI): University, College
EI 
- offer degrees
	- a degree has a program to follow
		- a course curriculum
			- has courses
				- has a syllabus
                                - has reference material
                                - has a faculty
                                - has a set of students

Students
   - register for a degree
   - are at a particular year / semester in a program
   - register for a set of classes
   - have a report card 

Faculty 
   - teaches a course
   - wants to share information on a topic
   - wants to give feedback
   - wants to access students

*** Bottom-up approach
+ Students have FOAF info
+ Students enroll in classes
+ students have a report card
+ Students are registered for a degree
+ Students want to know about a subject
+ Students want to know what is on the exam
+ Students enroll into a degree program
+ Students want to know what a particular faculty says
+ students want to get previous exams for a particular class by a
  particular faculty
+ Students want to know if there are other references for a topic on a
  give subject

+ Faculty wants to teach a class
+ Faculty wants to access a student
+ Faculty wants to recommend a reading assignment
+ Faculty wants to give notes or handouts for a course
+ Faculty wants to give homework for a group of students
+ Faculty teaches a subject to a group of students

+ courses are part of a curriculum
+ courses have a syllabus
+ courses have classes
+ Courses have grades
+ Courses have credit
+ Courses can be theory, lab or project oriented

+ Classes have students
+ Classes are taught by faculty
+ Classes have handouts
+ Classes have exams

+ Syllabus has Learning Objectives, Topics, Description
+ Syllabus has reference books
+ Syllabus has external links 

** step 5: 

* decisions made
* tools
